services:
  api:
    build: ./backend  
    ports:
      - "8000:8000"      
    volumes:
      - ./backend:/backend
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/frontend/build

  nginx:
    build:
      context: ./nginx
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - react_build:/var/www/frontend
    depends_on:
      - api
      - frontend
  
  db:
    image: postgres:latest
    container_name: postgres_db1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_SERVER: postgres_db1
      POSTGRES_PORT: 5432
    ports:
    - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 20s

volumes:
  postgres_data:
  react_build: