# Generated by Django 4.2.7 on 2023-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rest_Api",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField()),
                ("error_message", models.TextField(blank=True)),
                ("request", models.TextField(blank=True)),
                ("response", models.TextField(blank=True)),
            ],
        ),
    ]
