name: Docker Image CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/main

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Create env file
      run: |
          touch .env
          echo "${{ secrets.SERVER_ENV_PROD }}" > .env
          cat .env
          
    - name: Build image
      run: docker compose -f docker-compose.yml build
    - name: Push image to DO Container Registry
      run: docker compose -f docker-compose.yml push

  
